name: Gradle Build

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'graalvm'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Run Gradle test
      run: ./gradlew test
