name: Gradle Build

on: [push, pull_request]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Java
      uses: actions/setup-java@v5
      with:
        distribution: 'graalvm'
        java-version: '21'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5
    - name: Build
      run: ./gradlew build
    - name: Test
      run: ./gradlew test
    - name: Create Jars
      run: ./gradlew jar fatJar
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs
